// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6Rh7wJm53IZT4Jo7Z6rSdjc3mU1jeENM',
    appId: '1:617821993230:web:7ee5a24722f9d420453f5f',
    messagingSenderId: '617821993230',
    projectId: 'vibescape-872af',
    authDomain: 'vibescape-872af.firebaseapp.com',
    storageBucket: 'vibescape-872af.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABNrIQhs9CWW51jwf9R1Ofa8IoITyCmtM',
    appId: '1:617821993230:android:02d0bac991858496453f5f',
    messagingSenderId: '617821993230',
    projectId: 'vibescape-872af',
    storageBucket: 'vibescape-872af.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGGDxzuzdB1LjlKzCE8zkJ9PDqPa0-vck',
    appId: '1:617821993230:ios:d2c08349b1085fa3453f5f',
    messagingSenderId: '617821993230',
    projectId: 'vibescape-872af',
    storageBucket: 'vibescape-872af.firebasestorage.app',
    iosBundleId: 'com.example.vibescapeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGGDxzuzdB1LjlKzCE8zkJ9PDqPa0-vck',
    appId: '1:617821993230:ios:d2c08349b1085fa3453f5f',
    messagingSenderId: '617821993230',
    projectId: 'vibescape-872af',
    storageBucket: 'vibescape-872af.firebasestorage.app',
    iosBundleId: 'com.example.vibescapeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6Rh7wJm53IZT4Jo7Z6rSdjc3mU1jeENM',
    appId: '1:617821993230:web:10a17d08f7fb3ca5453f5f',
    messagingSenderId: '617821993230',
    projectId: 'vibescape-872af',
    authDomain: 'vibescape-872af.firebaseapp.com',
    storageBucket: 'vibescape-872af.firebasestorage.app',
  );
}
